// Called as a plain function from CarePlanCard.jsx — returns an HTML string.
// Accepts recipientName as a pre-built string (not the raw recipient object)
// so the caller controls name resolution (handles both joined data and array lookup).
export default function CarePlanPrint({ plan, recipientName }) {
  const goals = Array.isArray(plan.goals) ? plan.goals.filter(Boolean) : [];
  const updatedAt = plan.updated_at
    ? new Date(plan.updated_at).toLocaleDateString()
    : 'N/A';

  const goalsHtml = goals.length > 0
    ? `<div class="section">
        <h2>Goals</h2>
        ${goals.map(goal => `
          <div class="goal-item">
            <span class="bullet">&#8227;</span>
            <span>${goal}</span>
          </div>
        `).join('')}
      </div>`
    : '';

  const descriptionHtml = plan.description
    ? `<div class="section">
        <h2>Description</h2>
        <div class="notes">
          ${plan.description.split('\n').map(line => `<p style="margin: 6px 0;">${line}</p>`).join('')}
        </div>
      </div>`
    : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${plan.title || 'Care Plan'} — ${recipientName || 'Care Plan'}</title>
      <style>
        @page { margin: 1.5cm; }

        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }

        .header {
          border-bottom: 3px solid #9333ea;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }

        .header h1 {
          margin: 0 0 6px;
          color: #9333ea;
          font-size: 28px;
        }

        .header .meta {
          color: #555;
          font-size: 15px;
          line-height: 1.8;
        }

        .status-badge {
          display: inline-block;
          margin-top: 8px;
          padding: 2px 10px;
          border-radius: 12px;
          font-size: 13px;
          font-weight: bold;
          background: #e9d5ff;
          color: #6b21a8;
        }

        .section {
          margin-bottom: 28px;
          page-break-inside: avoid;
        }

        .section h2 {
          color: #9333ea;
          font-size: 18px;
          border-bottom: 2px solid #e9d5ff;
          padding-bottom: 6px;
          margin-bottom: 14px;
        }

        .goal-item {
          display: flex;
          align-items: flex-start;
          gap: 10px;
          padding: 8px 12px;
          margin-bottom: 8px;
          background: #f8f4ff;
          border-left: 3px solid #9333ea;
          border-radius: 4px;
        }

        .bullet {
          color: #9333ea;
          font-size: 18px;
          line-height: 1.4;
          flex-shrink: 0;
        }

        .notes {
          background: #f0f9ff;
          padding: 14px;
          border-radius: 4px;
          border-left: 3px solid #3b82f6;
        }

        .footer {
          margin-top: 40px;
          padding-top: 16px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          color: #888;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${plan.title || 'Care Plan'}</h1>
        <div class="meta">
          <strong>Care Recipient:</strong> ${recipientName || 'N/A'}<br>
          <strong>Last Updated:</strong> ${updatedAt}
        </div>
        <div class="status-badge">${plan.status || 'draft'}</div>
      </div>

      ${descriptionHtml}
      ${goalsHtml}

      <div class="footer">
        <p>Generated by FamilyCare.Help Care Plan Builder</p>
        <p style="color: #e07a5f;">This care plan is for informational purposes only. Always consult healthcare professionals for medical decisions.</p>
      </div>
    </body>
    </html>
  `;
}
