// Curated medical term lists for autocomplete suggestions
// These are common terms used in family caregiving contexts

export const CONDITIONS = [
  "Alzheimer's Disease",
  "Amyotrophic Lateral Sclerosis (ALS)",
  "Anemia",
  "Anxiety Disorder",
  "Arthritis (Osteoarthritis)",
  "Arthritis (Rheumatoid)",
  "Asthma",
  "Atrial Fibrillation",
  "Autism Spectrum Disorder",
  "Bipolar Disorder",
  "Bladder Incontinence",
  "Blood Clot (DVT)",
  "Breast Cancer",
  "Bronchitis (Chronic)",
  "Cancer (General)",
  "Cardiomyopathy",
  "Cataracts",
  "Celiac Disease",
  "Cerebral Palsy",
  "Chronic Fatigue Syndrome",
  "Chronic Kidney Disease",
  "Chronic Pain Syndrome",
  "Cirrhosis",
  "Colon Cancer",
  "Congestive Heart Failure",
  "COPD (Chronic Obstructive Pulmonary Disease)",
  "Coronary Artery Disease",
  "Crohn's Disease",
  "Cystic Fibrosis",
  "Deep Vein Thrombosis",
  "Dementia",
  "Dementia (Lewy Body)",
  "Dementia (Vascular)",
  "Depression (Major Depressive Disorder)",
  "Diabetes Type 1",
  "Diabetes Type 2",
  "Diabetic Neuropathy",
  "Down Syndrome",
  "Eating Disorder",
  "Emphysema",
  "Epilepsy",
  "Fibromyalgia",
  "Frontotemporal Dementia",
  "GERD (Acid Reflux)",
  "Glaucoma",
  "Gout",
  "Heart Attack (Myocardial Infarction)",
  "Heart Disease",
  "Hepatitis B",
  "Hepatitis C",
  "High Blood Pressure (Hypertension)",
  "High Cholesterol (Hyperlipidemia)",
  "Hip Fracture",
  "HIV/AIDS",
  "Huntington's Disease",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Irritable Bowel Syndrome (IBS)",
  "Kidney Failure",
  "Liver Disease",
  "Lung Cancer",
  "Lupus (Systemic Lupus Erythematosus)",
  "Macular Degeneration",
  "Melanoma",
  "Migraine",
  "Multiple Sclerosis (MS)",
  "Muscular Dystrophy",
  "Neuropathy (Peripheral)",
  "Obesity",
  "Osteoporosis",
  "Parkinson's Disease",
  "Peripheral Artery Disease",
  "Pneumonia",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Prostate Cancer",
  "Psoriasis",
  "Pulmonary Embolism",
  "Pulmonary Fibrosis",
  "Schizophrenia",
  "Scoliosis",
  "Seizure Disorder",
  "Sickle Cell Disease",
  "Sleep Apnea",
  "Spinal Cord Injury",
  "Spinal Stenosis",
  "Stroke",
  "Thyroid Disease",
  "Traumatic Brain Injury (TBI)",
  "Tuberculosis",
  "Ulcerative Colitis",
  "Urinary Tract Infection (Chronic)",
];

export const ALLERGIES = [
  // Drug allergies
  "Penicillin",
  "Amoxicillin",
  "Ampicillin",
  "Sulfa Drugs (Sulfonamides)",
  "Aspirin",
  "Ibuprofen (Advil/Motrin)",
  "Naproxen (Aleve)",
  "Acetaminophen (Tylenol)",
  "Codeine",
  "Morphine",
  "Tramadol",
  "Cephalosporins",
  "Erythromycin",
  "Tetracycline",
  "Ciprofloxacin",
  "Fluoroquinolones",
  "Metformin",
  "Lisinopril",
  "Statins",
  "Insulin",
  "Contrast Dye (Iodine)",
  "Latex",
  "Lidocaine",
  "Novocaine",
  "Anesthesia (General)",
  "Heparin",
  "Warfarin",
  // Food allergies
  "Peanuts",
  "Tree Nuts",
  "Shellfish",
  "Fish",
  "Milk/Dairy",
  "Eggs",
  "Wheat/Gluten",
  "Soy",
  "Sesame",
  "Corn",
  "Strawberries",
  "Citrus Fruits",
  "Chocolate",
  "Honey",
  // Environmental allergies
  "Bee Stings",
  "Wasp Stings",
  "Dust Mites",
  "Mold",
  "Pollen",
  "Pet Dander (Cats)",
  "Pet Dander (Dogs)",
  "Grass",
  "Ragweed",
  "Perfume/Fragrances",
  "Nickel",
  "Adhesive/Tape",
];

export const DIETARY_RESTRICTIONS = [
  "Diabetic Diet",
  "Low Sodium",
  "Low Potassium",
  "Low Phosphorus",
  "Low Sugar",
  "Low Fat/Low Cholesterol",
  "Heart-Healthy Diet",
  "Renal Diet (Kidney-Friendly)",
  "Gluten-Free",
  "Lactose-Free",
  "Dairy-Free",
  "Vegetarian",
  "Vegan",
  "Kosher",
  "Halal",
  "Soft/Pureed Foods",
  "Thickened Liquids",
  "Mechanical Soft Diet",
  "High Protein",
  "High Fiber",
  "Low Fiber",
  "Clear Liquid Diet",
  "Full Liquid Diet",
  "No Raw Foods",
  "No Grapefruit (Medication Interaction)",
  "Nut-Free",
  "Egg-Free",
  "Soy-Free",
  "Low FODMAP",
  "Anti-Inflammatory Diet",
  "Mediterranean Diet",
  "DASH Diet",
  "Ketogenic Diet",
  "Calorie Restricted",
  "Tube Feeding (Enteral)",
];

export const MEDICAL_EVENTS = [
  "Hip Replacement Surgery",
  "Knee Replacement Surgery",
  "Shoulder Replacement Surgery",
  "Cataract Surgery",
  "Heart Bypass Surgery (CABG)",
  "Heart Stent Placement",
  "Pacemaker Implant",
  "Defibrillator (ICD) Implant",
  "Heart Valve Replacement",
  "Appendectomy",
  "Gallbladder Removal (Cholecystectomy)",
  "Hernia Repair",
  "Spinal Fusion Surgery",
  "Back Surgery (Laminectomy)",
  "Mastectomy",
  "Lumpectomy",
  "Prostate Surgery",
  "Hysterectomy",
  "Colostomy/Ileostomy",
  "Kidney Transplant",
  "Liver Transplant",
  "Heart Transplant",
  "Dialysis Started",
  "Chemotherapy",
  "Radiation Therapy",
  "Heart Attack",
  "Stroke",
  "TIA (Mini-Stroke)",
  "Pulmonary Embolism",
  "Blood Transfusion",
  "Pneumonia Hospitalization",
  "COVID-19 Hospitalization",
  "Fall Injury",
  "Hip Fracture",
  "Broken Bone",
  "Concussion/Head Injury",
  "Seizure (First)",
  "Diagnosis - Alzheimer's",
  "Diagnosis - Cancer",
  "Diagnosis - Diabetes",
  "Diagnosis - Heart Disease",
  "Diagnosis - Parkinson's",
  "ICU Admission",
  "Ventilator Support",
  "Feeding Tube Placed",
  "Tracheostomy",
  "Amputation",
  "Skin Graft",
  "Physical Rehab Started",
  "Moved to Assisted Living",
  "Home Health Started",
  "Hospice Care Started",
];

// Helper to filter any list by search query
export function filterMedicalTerms(list, query) {
  if (!query || query.length < 1) return [];
  const lower = query.toLowerCase();
  return list
    .filter(item => item.toLowerCase().includes(lower))
    .slice(0, 8);
}
