// Shared print utilities — used by all print templates in the app.
// Pattern: open a new blank tab, write a complete HTML document, then print after 500ms
// so the browser has time to render before the dialog appears.

export function printDocument(html: string): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 500);
}

export function buildPrintStyles(accentColor = '#4F46E5'): string {
  return `<style>
    @page { margin: 1.5cm; }
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: ${accentColor}; margin: 0 0 6px; font-size: 26px; }
    h2 { color: ${accentColor}; font-size: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 12px; margin-top: 0; }
    .header { border-bottom: 3px solid ${accentColor}; padding-bottom: 16px; margin-bottom: 24px; }
    .meta { color: #555; font-size: 14px; line-height: 1.8; margin-top: 4px; }
    .section { margin-bottom: 24px; page-break-inside: avoid; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
    .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
    .row:last-child { border-bottom: none; }
    .card { background: #f9fafb; border-left: 3px solid ${accentColor}; border-radius: 4px; padding: 10px 14px; margin-bottom: 8px; font-size: 14px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #e5e7eb; text-align: center; color: #888; font-size: 12px; }
  </style>`;
}

export function buildPrintHeader(opts: {
  title: string;
  subtitle?: string;
  meta?: string;
}): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  return `<div class="header">
    <h1>${opts.title}</h1>
    ${opts.subtitle ? `<div class="meta"><strong>${opts.subtitle}</strong></div>` : ''}
    ${opts.meta ? `<div class="meta">${opts.meta}</div>` : ''}
    <div class="meta" style="color: #999; font-size: 12px; margin-top: 4px;">Printed: ${date}</div>
  </div>`;
}

export function buildPrintFooter(): string {
  return `<div class="footer">
    <p>Generated by FamilyCare.Help</p>
    <p style="color: #e07a5f;">For caregiving coordination only. Always consult healthcare professionals for medical decisions.</p>
  </div>`;
}
