import { lazy } from 'react';
import __Layout from './Layout.jsx';

export const PAGES = {
    "Appointments": lazy(() => import('./pages/Appointments')),
    "Calendar": lazy(() => import('./pages/Calendar')),
    "CareNotes": lazy(() => import('./pages/CareNotes')),
    "CarePlanBuilder": lazy(() => import('./pages/CarePlanBuilder')),
    "CarePlans": lazy(() => import('./pages/CarePlans')),
    "CareRecipients": lazy(() => import('./pages/CareRecipients')),
    "Checkout": lazy(() => import('./pages/Checkout')),
    "ClientAppointments": lazy(() => import('./pages/ClientAppointments')),
    "ClientMedicationLog": lazy(() => import('./pages/ClientMedicationLog')),
    "ClientPortal": lazy(() => import('./pages/ClientPortal')),
    "ClientTasks": lazy(() => import('./pages/ClientTasks')),
    "ClientUpdates": lazy(() => import('./pages/ClientUpdates')),
    "Collaboration": lazy(() => import('./pages/Collaboration')),
    "CommunicationHub": lazy(() => import('./pages/CommunicationHub')),
    "CookiePolicy": lazy(() => import('./pages/CookiePolicy')),
    "Dashboard": lazy(() => import('./pages/Dashboard')),
    "Diagnostics": lazy(() => import('./pages/Diagnostics')),
    "Documents": lazy(() => import('./pages/Documents')),
    "Emergency": lazy(() => import('./pages/Emergency')),
    "EmergencyProfile": lazy(() => import('./pages/EmergencyProfile')),
    "FAQ": lazy(() => import('./pages/FAQ')),
    "Landing": lazy(() => import('./pages/Landing')),
    "LegalDisclosure": lazy(() => import('./pages/LegalDisclosure')),
    "MedicationLog": lazy(() => import('./pages/MedicationLog')),
    "Medications": lazy(() => import('./pages/Medications')),
    "Messages": lazy(() => import('./pages/Messages')),
    "PrivacyPolicy": lazy(() => import('./pages/PrivacyPolicy')),
    "Receipts": lazy(() => import('./pages/Receipts')),
    "RecipientProfile": lazy(() => import('./pages/RecipientProfile')),
    "RecordRetentionPolicy": lazy(() => import('./pages/RecordRetentionPolicy')),
    "Refills": lazy(() => import('./pages/Refills')),
    "Reports": lazy(() => import('./pages/Reports')),
    "Scheduling": lazy(() => import('./pages/Scheduling')),
    "Settings": lazy(() => import('./pages/Settings')),
    "ShiftHandoff": lazy(() => import('./pages/ShiftHandoff')),
    "Tasks": lazy(() => import('./pages/Tasks')),
    "Team": lazy(() => import('./pages/Team')),
    "TermsOfService": lazy(() => import('./pages/TermsOfService')),
    "Today": lazy(() => import('./pages/Today')),
};

export const pagesConfig = {
    mainPage: "Dashboard",
    Pages: PAGES,
    Layout: __Layout,
};
